server:
  port: 20020
  monitoringPort: 20021
  # using clustering would also fork tests
  clustering: false

# send emails to a fake smtp server started during integration tests
email:
  transport:
    options:
      direct: false
      host: localhost
      port: 20030
      secure: false
      ignoreTLS: true

# in memory sqlite persistence
persistence:
  options:
    dialect: sqlite
    storage: ':memory:'

logging:
  transports:
    sentry:
      module: sentry
      dsn: https://a7da0ab444914a3881f7557170290009@sentry.dhatim.it/17
      level: error
    graylog:
      module: graylog_ovh
      graylogHost: gra2.logs.ovh.com
      graylogOvhTokenValue: 6b6c4303-8bb8-4821-9b8f-d7af4f327804
      level: info
  loggers:
    sql:
      transports: [console, sentry, graylog]
      level: debug
    http:
      transports: [console, sentry, graylog]
      level: debug
    email:
      transports: [console, sentry, graylog]
      level: debug
    login:
      transports: [console, sentry, graylog]
      level: debug
    sso:
      transports: [console, sentry, graylog]
      level: debug

#logging:
#  loggers:
#    sql:
#      transports: [console]
#      level: debug
#    http:
#      transports: [console]
#      level: debug
#    email:
#      transports: [console]
#      level: debug
#    login:
#      transports: [console]
#      level: debug
#    sso:
#      transports: [console]
#      level: debug
