server:
  port: 20020
  monitoringPort: 20021
  # using clustering would also fork tests
  clustering: false

# send emails to a fake smtp server started during integration tests
email:
  transport:
    options:
      direct: false
      host: localhost
      port: 20030
      secure: false
      ignoreTLS: true

# in memory sqlite persistence
persistence:
  options:
    dialect: sqlite
    storage: ':memory:'

logging:
  transports:
    sentry:
      module: sentry
      dsn: https://a7da0ab444914a3881f7557170290009@sentry.dhatim.it/17
      level: error
    graylog:
      module: graylog_ovh
      graylogHost: gra2.logs.ovh.com
      graylogOvhTokenValue: 5c2b5cd8-837a-4d2c-a61e-8bdbca90f19a
      level: debug
    graylog_audit:
      module: graylog_ovh
      graylogHost: gra2.logs.ovh.com
      graylogOvhTokenValue: 5c2b5cd8-837a-4d2c-a61e-8bdbca90f19a
      level: info
  loggers:
    audit:
      transports: [console, graylog_audit]
      level: info
    sql:
      transports: [console, sentry]
      level: info
    http:
      transports: [console, sentry]
      level: warning
    email:
      transports: [console, sentry]
      level: info
    login:
      transports: [console, sentry]
      level: info
    sso:
      transports: [console, sentry]
      level: info

#logging:
#  loggers:
#    sql:
#      transports: [console]
#      level: debug
#    http:
#      transports: [console]
#      level: debug
#    email:
#      transports: [console]
#      level: debug
#    login:
#      transports: [console]
#      level: debug
#    sso:
#      transports: [console]
#      level: debug
